services:
  # Backend FastAPI Service
  - type: web
    name: algorithm-visualizer-api
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
    healthCheckPath: /docs
    plan: free

  # Frontend Next.js Service
  - type: web
    name: algorithm-visualizer-web
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PYTHON_BACKEND_URL
        sync: false
    healthCheckPath: /
    plan: free
